[package]
name = "e2e"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "e2e"

[[example]]
name = "collection_lifecycle"

[[example]]
name = "share_view"

[dependencies]
chrono = { workspace = true }
eyre = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
